### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by GazorHuman** [Sayrix/ticket-bot#1]
Hey! i got some error maybe you can help me ? :D
https://pastebin.com/gNNtiNQj
Using node.js 14

**Comment by Sayrix** [comment]
Use nodejs 16.x or 17.x

**Comment by GazorHuman** [comment]
using node.js 16 got module not found error
https://pastebin.com/0X2c54xs
already download package from package.json

**Comment by GazorHuman** [comment]
does the bot has a prefix?

**Comment by Sayrix** [comment]
> does the bot has a prefix?

No it's slash commands lol
