### ISSUE TITLE
How do i add a image

### ISSUE THREAD

**Issue by saudaalseri** [Sayrix/Ticket-Bot#109]
how do i add a image in the open ticket embed  ?

**Comment by Sayrix** [comment]
in the locales/<your language>.json

**Comment by saudaalseri** [comment]
{
  "embeds": {
    "openTicket": {
      "title": "Open a ticket",
      "description": "Click on the button to start opening a ticket",
      "footer": {
        "text": ""
      }


i dont see that i can add a image

**Comment by Sayrix** [comment]
You need to add it manually

**Comment by Sayrix** [comment]
read the doc of discord about embeds

**Comment by saudaalseri** [comment]
> You need to add it manually read the doc of discord about embeds

ok thx i will be lookin in that

**Comment by saudaalseri** [comment]
but wait i have tried to add it manually it didn't work i remember it didn't put it in the main.js file

**Comment by saudaalseri** [comment]
And. I still do not know how to do it

**Comment by saudaalseri** [comment]
@Sayrix
