### ISSUE TITLE
Extinction du bot

### ISSUE THREAD

**Issue by Guillaume0001** [Sayrix/Ticket-Bot#112]
Bonjour, lorsque je lance le bot, il fonctionne niquel puis au bout de je dirais 21 heures de fonctionnement il s'éteint tout seul sans erreurs. J'ai installer le bot sur Linux avec un screen. Cela vient il du code où cela peut provenir de mon screen 🤔 ?
Belle soirée.

**Comment by Sayrix** [comment]
utilise pm2 au lieu de screen

**Comment by Guillaume0001** [comment]
Merci je vais essayer
