### ISSUE TITLE
Bug Bot

### ISSUE THREAD

**Issue by Demon-Galaxie** [Sayrix/Ticket-Bot#116]
Hi,

I currently have a problem with your bot, when I start it on my host no problem but as soon as I try to open a ticket, it puts the bot thinking for an unlimited time, on my console I have a error but I don't really understand it (see image), can you explain to me what is wrong please?

Thanks in advance
![Capture d’écran (92)](https://user-images.githubusercontent.com/88180505/221379450-f4508fb7-7d6f-4acf-bacf-08514b99c474.png)

**Comment by Sayrix** [comment]
Hi what is the version of your ticket bot ?

**Comment by Demon-Galaxie** [comment]
version : 2.0.8.3

**Comment by Demon-Galaxie** [comment]
![image_2023-02-25_221007098](https://user-images.githubusercontent.com/88180505/221379697-892bda04-7baf-4ac4-bd42-93a125dd859f.png)

**Comment by Sayrix** [comment]
Did you changed something ?

**Comment by Demon-Galaxie** [comment]
No, I just removed the example from the config and token file (if I removed it, it gave me an error) and I configured the bot

**Comment by Sayrix** [comment]
That's strange

**Comment by Sayrix** [comment]
it should work

**Comment by Demon-Galaxie** [comment]
yes it's strange but maybe because the modules were installed automatically from the host (when I first launched the host, there was no node_modules so they were installed automatically) is what it can come from there, if yes can be can you send me your node_modules so that I test

**Comment by Sayrix** [comment]
Faut jamais faire ça t'es malade ou quoi

**Comment by Demon-Galaxie** [comment]
Ah vous êtes français ça m'arrange :), faut jamais faire quoi prendre un module d'autre part ou que l'hébergeur installe automatiquement un module ???

**Comment by Sayrix** [comment]
Les node_modules sont build par rapport à ta machine donc si tu poste les node_modules sa fonctionne pas faut jamais faire ça

**Comment by Demon-Galaxie** [comment]
Ah ok je savais pas c bon à savoir

**Comment by Demon-Galaxie** [comment]
Du coup jsp d'où ça peut venir le bug mais après ça vient peut être de l'hébergeur ou d'une mal config de ma part, je vais me pencher dessus demain

**Comment by Demon-Galaxie** [comment]
J'ai essayé aujourd'hui de relancer le bot mais le bot se lance bien mais il ne crée plus le message ouvrir un billet et il y a une autre erreur dans la console, c vrmt bizarre car je n'ai pas touché au bot depuis hier ... 
![Capture d’écran 2023-02-26 102006](https://user-images.githubusercontent.com/88180505/221402403-5d151d48-f5b8-4223-8baf-e566d6b5943b.png)

**Comment by Demon-Galaxie** [comment]
Je te montre en peu ma config, dis moi si tu vois quelque chose d'anormal
![Capture d’écran (95)](https://user-images.githubusercontent.com/88180505/221403327-b97c4d24-ccb0-42a9-8a01-ad8dbc93e6cb.png)
![Capture d’écran (94)](https://user-images.githubusercontent.com/88180505/221403328-84a4550f-2b47-43a6-bc7b-ecab654c0e78.png)

**Comment by Sayrix** [comment]
Essaie avec cette PR stp https://github.com/Sayrix/Ticket-Bot/pull/117

**Comment by Demon-Galaxie** [comment]
J'ai test mais ça fait crash le serv et Visual Code dit qu'il y a une erreur 

![Capture d’écran (98)](https://user-images.githubusercontent.com/88180505/221411551-98b5f9f9-a188-4ff1-98a3-edef89c40e66.png)
![Capture d’écran (97)](https://user-images.githubusercontent.com/88180505/221411552-b061504d-a1af-4e84-8d71-91a3169c0f76.png)

**Comment by Sayrix** [comment]
T'a mal importé la PR

**Comment by Demon-Galaxie** [comment]
Ah ok, j'avais pas compris que ça fonctionner comme Git Graph, qu'il fallait supp les lignes rouges, c nickel maintenant tout fonctionne parfaitement sauf le claim qui me dit que je suis pas staff alors que j'ai le role staff que j'ai config (j'ai réussi a fermer le ticket donc j'ai bien le bon role) après ça n'a rien de dérangeant donc trkl, merci et bonne journée ^^

**Comment by Sayrix** [comment]
https://github.com/Sayrix/Ticket-Bot/pull/117/files Tu clique ici
![image](https://user-images.githubusercontent.com/43046854/221412317-beb8fcde-ae85-4b66-8c79-4c169a329bb8.png)

**Comment by Demon-Galaxie** [comment]
Ah ok mdrrr, oep je viens de review, merci encore
