### ISSUE TITLE
Ticket cant be made

### ISSUE THREAD

**Issue by XXILTeun** [Sayrix/Ticket-Bot#123]
this is the error i get: 
_**DiscordAPIError[50035]: Invalid Form Body
parent_id[NUMBER_TYPE_COERCE]: Value "" is not snowflake.
    at SequentialHandler.runRequest (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async GuildChannelManager.create (/BaitSMP-Ticket/node_modules/discord.js/src/managers/GuildChannelManager.js:170:18) {
  rawError: {
    code: 50035,
    errors: { parent_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/guilds/972818362566590464/channels',
  requestBody: {
    files: undefined,
    json: {
      name: 'Ticket-TeunHessels-0',
      topic: undefined,
      type: undefined,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: '',
      position: undefined,
      permission_overwrites: [Array],
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_auto_archive_duration: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    }
  }
} Promise {
  <rejected> DiscordAPIError[50035]: Invalid Form Body
  parent_id[NUMBER_TYPE_COERCE]: Value "" is not snowflake.
      at SequentialHandler.runRequest (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:933:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:712:14)
      at async REST.request (/BaitSMP-Ticket/node_modules/@discordjs/rest/dist/index.js:1321:22)
      at async GuildChannelManager.create (/BaitSMP-Ticket/node_modules/discord.js/src/managers/GuildChannelManager.js:170:18) {
    rawError: { code: 50035, errors: [Object], message: 'Invalid Form Body' },
    code: 50035,
    status: 400,
    method: 'POST',
    url: 'https://discord.com/api/v10/guilds/972818362566590464/channels',
    requestBody: { files: undefined, json: [Object] }
  }
} undefined **_

**Comment by Sayrix** [comment]
Check your config you did something wrong

**Comment by XXILTeun** [comment]
{
	"clientId": "1088485744416407652", // The id of the discord bot
	"guildId": "1088482683992145990", // The id of the discord server
	"mainColor": "f6c42f", // The hex color of the embeds by default
	"lang": "main", // If you want to set english please set "main"

	"closeTicketCategoryId": "1088484719508869120", // The id of the category where a closed ticket will be moved to
	"openTicketChannelId": "1088485253330505890", // The id of the channel where the message to create a ticket will be sent

	"ticketTypes": [
		// You have a limit of 25 types (the limit of Discord)
		{
			"codeName": "category-one", // The name need to be in lowercase
			"name": "Category One", // The name that will be displayed in the ticket
			"description": "Description of Category One", // The description of the Ticket in Create Ticket Menu
			"emoji": "💡", // The emoji of the type (can be blank)
			"color": "", // Can be a hex color or blank to use the main color
			"categoryId": "", // The category id where the tickets will be created
			"customDescription": "Please explain your suggestion in detail. If you have any images, please attach them to your message.\n\nReason: REASON", // The custom description of the ticket type (set to blank to use the default description)
			"askReason": true // If the bot should ask the reason of the ticket
		},
		{
			"codeName": "category-two", // The name need to be in lowercase
			"name": "Category Two", // The name that will be displayed in the ticket
			"description": "Description of Category Two", // The description of the Ticket in Create Ticket Menu
			"emoji": "🛑", // The emoji of the type (can be blank)
			"color": "#f8312f", // Can be a hex color or blank to use the main color
			"categoryId": "", // The category id where the tickets will be created
			"customDescription": "Please explain your report in detail. If you have any images, please attach them to your message.\n\nReason: REASON", // The custom description of the ticket type (set to blank to use the default description)
			"askReason": false // If the bot should ask the reason of the ticket
		},
		{
			"codeName": "other", // The name need to be in lowercase
			"name": "Other", // The name that will be displayed in the ticket
			"description": "Description of Category Other", // The description of the Ticket in Create Ticket Menu
			"emoji": "", // The emoji of the type (can be blank)
			"color": "", // Can be a hex color or blank to use the main color
			"categoryId": "", // The category id where the tickets will be created
			"customDescription": "", // The custom description of the ticket type (set to blank to use the default description)
			"askReason": false // If the bot should ask the reason of the ticket
		}
	],
	"ticketNameOption": "Ticket-TICKETCOUNT", // Here is all parameter: USERNAME, USERID, TICKETCOUNT
	"rolesWhoHaveAccessToTheTickets": [
		"1088482683992145990"
	], // Roles who can access to the tickets
	"rolesWhoCanNotCreateTickets": [""], // Roles who can	not create a tickets
	"pingRoleWhenOpened": true,
	"roleToPingWhenOpenedId": ["1088482683992145990"], // The role to ping when a ticket is opened
	"logs": true,
	"logsChannelId": "", // The id of the channel where the logs will be sent
	"claimButton": true,
	"whoCanCloseTicket": "STAFFONLY", // STAFFONLY (roles configured at "rolesWhoHaveAccessToTheTickets") or EVERYONE
	"closeButton": true, // If false the ticket can be closed only by doing /closes
	"askReasonWhenClosing": true, // If false the ticket will be closed without asking the reason
	"maxTicketOpened": 1 // The number of tickets the user can open while another one is already open. Set to 0 to unlimited
}

This is the config

**Comment by Sayrix** [comment]
You forgot to set categoryId

**Comment by Sayrix** [comment]
Send the error please
