### ISSUE TITLE
Change ticket name when ticket claimed

### ISSUE THREAD

**Issue by Sayrix** [Sayrix/Ticket-Bot#139]
### Discussed in https://github.com/Sayrix/Ticket-Bot/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **BlueSky-fur** April 17, 2023</sup>
For better oversight for staff-members i was thinking of the following idea

When you open a ticket it gets moved into the Open Tickets category as setup per user.

As soon as it gets claimed by a staff member the ticket could move into a new category (if choosen to setup in the config)
and the ticket then switches from its standard name to the name of the staffmember and the user that created the ticket

Example

Freshly Opened ticket name
`💌︱8・bluesky` 

when claimed would switch to a diffrent category if choosen so in config and then rename to

`💌︱staffusername・bluesky` 

Thanks in advance for your time to read this!

</div>

**Comment by Lucas6635** [comment]
sa serais pas mal comme ajout c'est vrai

**Comment by FSULiam** [comment]
hello i need help
