### ISSUE TITLE
Add warnings about the thing that the bot have some anonymous telemetry

### ISSUE THREAD

**Issue by Sayrix** [Sayrix/Ticket-Bot#148]
The bot sends several data to the metadata websocket server here is the list:

- The number of guilds where the bot is
- The number of users the bot have in cache
- The version of the ticket-bot
- The node.js version
- The os version
- The cpu version
- The cpu name
- The number of cpu cores
- The cpu arch
- The cpu model
- The process uptime
- The total ram
- The free ram
- The client name
- The client id
- The guild id

**⚠️⚠️⚠️ All these data are saved anonymously ⚠️⚠️⚠️**.

**Comment by zhiyan114** [comment]
Completed on 9ab69e6. Also added the ability for users to toggle the telemetry.
