### ISSUE TITLE
La methode pour corriger les commandes /

### ISSUE THREAD

**Issue by AzerothSixhten** [Sayrix/ticket-bot#15]
Les commandes ne sont disponibles que si votre bot a des autorisations "scopes" lui permettant, aller donc dans votre developper portal et dans OAuth2, puis choisissez vos scopes. Copiez l'adresse en bas et cliquez dessus pour inviter votre nouveau bot avec les autorisations ! Tout devrez être fonctionnel ensuite. Cela devrez donner un truc du style : 
![image](https://user-images.githubusercontent.com/76072277/155314361-3429a77f-81e3-468a-8f7e-1b499a9cd29a.png)

**Comment by Sayrix** [comment]
Don't use google translate plz
