### ISSUE TITLE
[CODE BUG] TRANCIPT EMBED

### ISSUE THREAD

**Issue by Bodeyibl** [Sayrix/ticket-bot#16]
Him i have a problem where the ticket embed/ticket trancipt doesnt log and send to the user, i tried allot but i dont know how to fix it. im new to coding thats why. 

Thank you in advance.

![image](https://user-images.githubusercontent.com/100451680/156052836-b10db381-c497-4316-8633-8c0ca4b58020.png)

**Comment by Sayrix** [comment]
yo do not have config ticket logs channel
