### ISSUE TITLE
Claimed Ticket Category

### ISSUE THREAD

**Issue by zhiyan114** [Sayrix/Ticket-Bot#168]
Based on the following discussion: #138

Context (@BlueSky-fur):
> For better oversight for staff-members i was thinking of the following idea
> 
> When you open a ticket it gets moved into the Open Tickets category as setup per user.
> 
> As soon as it gets claimed by a staff member the ticket could move into a new category (if choosen to setup in the config) and the ticket then switches from its standard name to the name of the staffmember and the user that created the ticket
> 
> Example
> 
> Freshly Opened ticket name `💌︱8・bluesky`
> 
> when claimed would switch to a diffrent category if choosen so in config and then rename to
> 
> `💌︱staffusername・bluesky`
> 
> Thanks in advance for your time to read this!

**Comment by BlueSky-fur** [comment]
Thanks man! <3

**Comment by zhiyan114** [comment]
Feature is done
