### ISSUE TITLE
Possibility to add images like this in the side

### ISSUE THREAD

**Issue by Sventt** [Sayrix/Ticket-Bot#169]
![image](https://github.com/Sayrix/Ticket-Bot/assets/58893063/1b9e45a5-d79c-4ea3-883c-ee3c9b1f8721)

**Comment by Sayrix** [comment]
It's in the /locales/LANGUAGE.json the embeds are in json so just check the doc of discord

**Comment by zhiyan114** [comment]
Ohh I see how it works. TypeScript did complaint when it tries to feed the configuration directly into embeds array so everything is constructed manually.

But ye, I'll add that to TS todo list.
