### ISSUE TITLE
How does custom domains work?

### ISSUE THREAD

**Issue by CodeMeZone** [Sayrix/Ticket-Bot#175]
**Is your feature request related to a problem? Please describe.**
I'm really not understanding how this works.

**Describe the solution you'd like**
Let us host the ticket data, you can go offline at anytime or this project can and will go under sooner or later.

**Additional context**
I don't care about paying, that's not the issue - I just don't trust anyone if data like that. Let us host our own.

**Comment by Sayrix** [comment]
Hi, custom domains are simply me adding your domain to a private server for sponsors. The tickets are saved anonymously on a different server. The service won't stop as long as there are still people using it.

**Comment by CodeMeZone** [comment]
Sooo.... about selfhosting.. Why even post this on github if you're going to paywall it. Just like any other paid ticket bot.

You already refuse to answer about self-hosting, yeah good confidence, let me run your web socket on my server....

**Comment by Sayrix** [comment]
Simply because I preferred to make open source the most important part of a ticket bot, which is the ticket bot and not its transcript system. If you don't trust the transcript api and don't want to buy its code, then don't use it.

**Comment by zhiyan114** [comment]
> Sooo.... about selfhosting.. Why even post this on github if you're going to paywall it. Just like any other paid ticket bot.
> 
> You already refuse to answer about self-hosting, yeah good confidence, let me run your web socket on my server....

As much as I agree with you, he is not required to open source all the component of the code. If privacy is an issue, you can always disable transcript and block any external connections you want or read the code and design your own transcript system.

P.S. I don't have access to source either.
