### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by eandrade92630** [Sayrix/Ticket-Bot#178]
**Is your feature request related to a problem? Please describe.**
Not a problem per se but having a docker container would eliminate the need to worry about dependencies and making sure it's all set up correctly.

**Describe the solution you'd like**
A docker container made for easy deployments and updates which would also make for easy backups and migrations.

**Comment by zhiyan114** [comment]
Awaiting for review https://github.com/Sayrix/Ticket-Bot/pull/179

otherwise, everything is working for me.
