### ISSUE TITLE
License Compliance

### ISSUE THREAD

**Issue by zhiyan114** [Sayrix/Ticket-Bot#212]
@Sayrix  Looks like there's some license issue that was detected by fossa (#206) but wasn't triggered during the PR checks. Can you verify which compliance is missing and which is false positive?

@Rafaelh9siX Please verify your source to ensure that they're are complying with the module's license. You can view the potential issue on [fossa](https://app.fossa.com/projects/git%2Bgithub.com%2FSayrix%2FTicket-Bot/refs/branch/main/942832a54d9edcb9fe6f5f39652a59a18eadd27a/browse/licenses). If you do find any, you can make a quick PR to fix it.

**Comment by Sayrix** [comment]
Yes, it comes from modules that django uses

**Comment by Sayrix** [comment]
![image](https://github.com/Sayrix/Ticket-Bot/assets/43046854/a67a733d-9bbc-452f-b763-b8c17a75d6a9)

**Comment by Rafaelh9siX** [comment]
I removed mysql-connector and psycopg2 from requirements.txt, I think that should solve the problem
