### ISSUE TITLE
help plssssss

### ISSUE THREAD

**Issue by emanuelgggggggg** [Sayrix/ticket-bot#23]
![image](https://user-images.githubusercontent.com/47868954/162301351-2397c7d8-f38e-45af-a0ec-db1cdd732509.png)
someone can help me?

**Comment by Sayrix** [comment]
Just read the error 🙃

**Comment by Owned67** [comment]
> ![image](https://user-images.githubusercontent.com/47868954/162301351-2397c7d8-f38e-45af-a0ec-db1cdd732509.png) someone can help me?

something wrong with your config apparently ;) dm if needed

**Comment by Owned67** [comment]
(node:21880) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:21880) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

**Comment by Sayrix** [comment]
It's not a error but a warning (:
