### ISSUE TITLE
per-category staff roles

### ISSUE THREAD

**Issue by camfsd** [Sayrix/Ticket-Bot#230]
Hey 👋

Instead of having a set of staff/ping roles for every category, it would be great if you could configure staff roles per-category. This makes having categories much more worthwhile.

**Comment by RaiRaii** [comment]
Well when i give the bot pretty much all permission except the admin role I get some errors. I maybe missed out something.

**Comment by camfsd** [comment]
> Well when i give the bot pretty much all permission except the admin role I get some errors. I maybe missed out something.
> 
> 
> 
> I guess it was here we should continue our convo? ^^

How does this relate to this enhancement?

**Comment by zhiyan114** [comment]
> > Well when i give the bot pretty much all permission except the admin role I get some errors. I maybe missed out something.
> > I guess it was here we should continue our convo? ^^
> 
> How does this relate to this enhancement?
> 
> Make a new issue please.

Oh sorry!
He made a comment on a push request related to this issue, so I thought he was asking for the progress on this feature and had him make future comments here instead.

@RaiRaii But yes, if it's an issue related to the bot, please create a separate bug issue please.

**Comment by RaiRaii** [comment]
> > > Well when i give the bot pretty much all permission except the admin role I get some errors. I maybe missed out something.
> > > I guess it was here we should continue our convo? ^^
> > 
> > 
> > How does this relate to this enhancement?
> > Make a new issue please.
> 
> Oh sorry! He made a comment on a push request related to this issue, so I thought he was asking for the progress on this feature and had him make future comments here instead.
> 
> @RaiRaii But yes, if it's an issue related to the bot, please create a separate bug issue please.

Well yeah, knowing the progress in this is absolutely a thing, this is the main issue I kinda have right now! 😁
