### ISSUE TITLE
Cant delte tickets

### ISSUE THREAD

**Issue by Valdblade** [Sayrix/ticket-bot#25]
After some time of the tickets being created the members cannot delete it and it gives this error within the console

TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role.
11|smticke |     at Function.resolve (/root/smticket/node_modules/discord.js/src/structures/PermissionOverwrites.js:184:28)
11|smticke |     at /root/smticket/node_modules/discord.js/src/structures/GuildChannel.js:318:87
11|smticke |     at Array.map (<anonymous>)
11|smticke |     at TextChannel.edit (/root/smticket/node_modules/discord.js/src/structures/GuildChannel.js:318:57)
11|smticke |     at InteractionCollector.<anonymous> (/root/smticket/events/interactionCreate.js:205:16)
11|smticke |     at InteractionCollector.emit (node:events:402:35)
11|smticke |     at InteractionCollector.handleCollect (/root/smticket/node_modules/discord.js/src/structures/interfaces/Collector.js:109:12)
11|smticke |     at runMicrotasks (<anonymous>)
11|smticke |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
11|smticke |   [Symbol(code)]: 'INVALID_TYPE'
11|smticke | }
11|smticke | (node:27848) DeprecationWarning: Passing strings for MessageEmbed#setAuthor is deprecated. Pass a sole object instead.
11|smticke | (Use `node --trace-deprecation ...` to show where the warning was created)
11|smticke | (node:27848) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

**Comment by FoxXxHater** [comment]
Some Times i have the same error. 
I fixed it with deleting the channelpermissionoverrite while closing the channel in the code.

**Comment by FoxXxHater** [comment]
![image](https://user-images.githubusercontent.com/54017453/169804399-f61066fa-b6dc-41a8-a4fa-99dca3465c33.png)


delete or comment this all (in the red box)

**Comment by FoxXxHater** [comment]
but it can be that always comes an error that a channel can not be found. At least that's the case for me. Whether that is now because ... no idea. XD

**Comment by 0x7da** [comment]
> but it can be that always comes an error that a channel can not be found. At least that's the case for me. Whether that is now because ... no idea. XD

You need to set the log channel in the config file.

**Comment by FoxXxHater** [comment]
@0x7da 

What? There is no option?!

**Comment by FoxXxHater** [comment]
@0x7da 

i have set the Log Channel 
![image](https://user-images.githubusercontent.com/54017453/170945769-621d1c8e-7758-418b-9c06-635490110b55.png)

**Comment by 0x7da** [comment]
> TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role.

give the bot manage, CHANNELS, or ADMIN. he cant delete Channels 
![image](https://user-images.githubusercontent.com/38230414/171664825-b58b2da7-3e0e-418a-a64a-8e1cdaa886c8.png)

**Comment by Migueldeeteenaa** [comment]
> Same issue, few hours after the ticket is opened, it is not possible to close it.
> 
> TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role. at Function.resolve (/home/tickets/ticket-bot/node_modules/discord.js/src/structures/PermissionOverwrites.js:184:28) at /home/tickets/ticket-bot/node_modules/discord.js/src/managers/GuildChannelManager.js:249:90 at Array.map () at GuildChannelManager.edit (/home/tickets/ticket-bot/node_modules/discord.js/src/managers/GuildChannelManager.js:249:60) at TextChannel.edit (/home/tickets/ticket-bot/node_modules/discord.js/src/structures/GuildChannel.js:275:32) at InteractionCollector. (/home/tickets/ticket-bot/events/interactionCreate.js:238:16) at InteractionCollector.emit (node:events:539:35) at InteractionCollector.handleCollect (/home/tickets/ticket-bot/node_modules/discord.js/src/structures/interfaces/Collector.js:109:12) at processTicksAndRejections (node:internal/process/task_queues:96:5) {

I have that problem too!
