### ISSUE TITLE
[Question] Django Framework

### ISSUE THREAD

**Issue by Vip3rLi0n** [Sayrix/Ticket-Bot#283]
Hi, I tried the dashboard but it didnt work nicely. Seems like theres missing static folder where it should've been there. I wonder if it could be fixed or readded? Since without it, it looks like literal text in html, lol.

**Comment by Sayrix** [comment]
@RafaelHGOliveira

**Comment by zhiyan114** [comment]
We might need to remove the source from the repo since both of us aren't knowledgeable to maintain it, and contributors aren't technically responsible to do so.

**Comment by Sayrix** [comment]
Yep
