### ISSUE TITLE
Not Worked Slash Commands

### ISSUE THREAD

**Issue by Benz-SQV** [Sayrix/ticket-bot#30]
![deploy-commands](https://user-images.githubusercontent.com/81667720/171122276-a0347a58-51de-43c7-81cb-daf7ce3ff641.png)
already start deploy-commands, but the commands in the bot is not show as suggestion like in ur video

![error](https://user-images.githubusercontent.com/81667720/171122562-d2169be7-bef4-41f0-be73-73cd30129a68.png)
and how to resolve this ?

**Comment by Sayrix** [comment]
You need to add your discord bot with the scope application.commands

**Comment by Benz-SQV** [comment]
![171122562-d2169be7-bef4-41f0-be73-73cd30129a68](https://user-images.githubusercontent.com/81667720/171384884-07449035-7d61-418e-ae00-86539d992088.png)

how to resolve this ?

**Comment by FoxXxHater** [comment]
> ![171122562-d2169be7-bef4-41f0-be73-73cd30129a68](https://user-images.githubusercontent.com/81667720/171384884-07449035-7d61-418e-ae00-86539d992088.png)
> 
> how to resolve this ?

As far as I know these are not real errors in this sense. These are only infos that tell you that you should rather update these commands/packages.

**Comment by 0x7da** [comment]
> > ![171122562-d2169be7-bef4-41f0-be73-73cd30129a68](https://user-images.githubusercontent.com/81667720/171384884-07449035-7d61-418e-ae00-86539d992088.png)
> > how to resolve this ?
> 
> As far as I know these are not real errors in this sense. These are only infos that tell you that you should rather update these commands/packages.

is a debug message isnt critical

**Comment by FoxXxHater** [comment]
> > > ![171122562-d2169be7-bef4-41f0-be73-73cd30129a68](https://user-images.githubusercontent.com/81667720/171384884-07449035-7d61-418e-ae00-86539d992088.png)
> > > how to resolve this ?
> > 
> > 
> > As far as I know these are not real errors in this sense. These are only infos that tell you that you should rather update these commands/packages.
> 
> is a debug message isnt critical

Well I say XD
