### ISSUE TITLE
Ticket closing and Bot sending DM to users.

### ISSUE THREAD

**Issue by xx7661** [Sayrix/Ticket-Bot#300]
**Is your feature request related to a problem? Please describe.**
Sometimes bot can't send dm to users and when you want to close a thread but want users to keep a transcript it would be impossible because they can't see the thread.

**Describe the solution you'd like**
Maybe have a toggle settings to only make users muted when a ticket is closed and keep them to be able to see it. before finally deleting or maybe AUTO deleting the ticket with a config as well.

Another problem I've seen is sometimes there are people who are trolling the ticket system, maybe have some filter or blacklist word / phrase that will instantly stop users from creating the ticket and timeout them from making tickets for a while.

**Comment by zhiyan114** [comment]
> Sometimes bot can't send dm to users and when you want to close a thread but want users to keep a transcript it would be impossible because they can't see the thread.

Most likely the user had their DM disabled, could you ask them to enable it?


> Another problem I've seen is sometimes there are people who are trolling the ticket system, maybe have some filter or blacklist word / phrase that will instantly stop users from creating the ticket and timeout them from making tickets for a while.

There's a `cantAccess` config, which you can add a ban role to for every category. I don't think an automatic filter would be effective at all since the user can theoretically fill in junk text and bypass it.
