### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by HBBrineCommands** [Sayrix/ticket-bot#32]
npm WARN deprecated @sapphire/snowflake@1.3.6: This version has been automatically deprecated by @favware/npm-deprecate. Please use a newer version.
npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)
npm WARN deprecated discord-api-types@0.22.0: No longer supported. Instal

**Comment by FoxXxHater** [comment]
We all have this XD
