### ISSUE TITLE
Slash Commands Not Work!

### ISSUE THREAD

**Issue by unpeekabl3** [Sayrix/ticket-bot#33]
![image](https://user-images.githubusercontent.com/87239155/171447739-cb2ef2a2-f2ea-45a4-bb99-b33592a306e9.png)

**Comment by 0x7da** [comment]
> > ![image](https://user-images.githubusercontent.com/87239155/171447739-cb2ef2a2-f2ea-45a4-bb99-b33592a306e9.png)
> 
> Use Node V13 or Higher start the file deploy-commands.js to run Slash Commands.

activate the bot intens ;-; "YOU ARE NOT AUTHORIZED TO PEFORM THIS ACTION ON THIS APPLICATION"

**Comment by Derpinou** [comment]
The bot don't have the scope appilaction.commands, so invite him with the correct link with the application.commands scope: https://discord.com/api/oauth2/authorize?client_id=APPLICATION_ID&permissions=0&scope=bot%20applications.commands
