### ISSUE TITLE
Bot Not Starting

### ISSUE THREAD

**Issue by user093209** [Sayrix/Ticket-Bot#350]
I try to start bot than show me error

up to date, audited 415 packages in 10s
126 packages are looking for funding
  run `npm fund` for details
5 low severity vulnerabilities
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
container@pterodactyl~ Server marked as running...
node:internal/modules/cjs/loader:1143
  throw err;
  ^
Error: Cannot find module '/home/container/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v18.20.2

**Comment by Sayrix** [comment]
Error: Cannot find module '/home/container/dist/index.js'

**Comment by Sayrix** [comment]
That's not a bug. It's your fault if there are this error. Just read the doc and you'll understand

**Comment by Sayrix** [comment]
Ask to your host.
