### ISSUE TITLE
Error that cause no ticket close and no logs

### ISSUE THREAD

**Issue by DOSEV5** [Sayrix/ticket-bot#41]
if (!userOrRole) throw new TypeError('INVALID_TYPE', 'parameter', 'User nor a Role');

it is in permissionoverwrite js:186
Everything os alright, but sometimes it just broke itself. And only way to fix it is to clear tickets without the bot and then restart it!

**Comment by muralianand12345** [comment]
This issue is from the new discord.js@14 ... they have changed the version 13 a bit

**Comment by Sayrix** [comment]
> This issue is from the new discord.js@14 ... they have changed the version 13 a bit 

Absolutely not, it's just that he didn't configure the bot

**Comment by DOSEV5** [comment]
> > This issue is from the new discord.js@14 ... they have changed the version 13 a bit 
> 
> Absolutely not, it's just that he didn't configure the bot

I did it corectly.

**Comment by DOSEV5** [comment]
> > This issue is from the new discord.js@14 ... they have changed the version 13 a bit 
> 
> Absolutely not, it's just that he didn't configure the bot

Other people have the same issues

**Comment by DOSEV5** [comment]
Any ideas because I configure it right?

**Comment by NovaGTX** [comment]
Something is definitely going on. Had it configured and working properly, then it starts crashing when trying to close tickets recently.
