### ISSUE TITLE
TS2417: Class static side 'typeof Client' incorrectly extends base class static side 'typeof BaseClient'.

### ISSUE THREAD

**Issue by ZAZOU-FR** [Sayrix/Ticket-Bot#427]
**Describe the bug**
Cannot build because of class type

**To Reproduce**
Build the container

**Version : 3.3.1**

`
Step 13/16 : RUN npm run build
 ---> Running in 49977c616b2f

> ticket-bot@3.3.1 build
> rimraf dist && tsc

node_modules/discord.js/typings/index.d.ts(986,14): error TS2417: Class static side 'typeof Client' incorrectly extends base class static side 'typeof BaseClient'.
  The types returned by 'on(...)' are incompatible between these types.
    Property '[Symbol.asyncDispose]' is missing in type 'AsyncIterableIterator<any>' but required in type 'AsyncIterator<any[], any, any>'.
src/events/ready.ts(92,13): error TS2339: Property 'send' does not exist on type 'DMChannel | PartialDMChannel | PartialGroupDMChannel | NewsChannel | StageChannel | TextChannel | PublicThreadChannel<...> | PrivateThreadChannel | VoiceChannel'.
  Property 'send' does not exist on type 'PartialGroupDMChannel'.
src/events/ready.ts(95,14): error TS7006: Parameter 'rMsg' implicitly has an 'any' type.
src/utils/close.ts(122,24): error TS2339: Property 'send' does not exist on type 'TextBasedChannel'.
  Property 'send' does not exist on type 'PartialGroupDMChannel'.
src/utils/close.ts(127,13): error TS7006: Parameter 'e' implicitly has an 'any' type.
src/utils/close.ts(145,24): error TS2339: Property 'send' does not exist on type 'TextBasedChannel'.
  Property 'send' does not exist on type 'PartialGroupDMChannel'.
src/utils/close.ts(156,12): error TS7006: Parameter 'e' implicitly has an 'any' type.
The command '/bin/sh -c npm run build' returned a non-zero code: 2
ERROR: Service 'bot' failed to build : Build failed
`

**Comment by zhiyan114** [comment]
Try using the latest repo source since it was recently package updated. Updating package from older source will lead to error due to small breaking-changes djs likes to make.

**Comment by ZAZOU-FR** [comment]
I forced to stick to some version onto the package.json file. Version used into my docker container was too high.
