### ISSUE TITLE
Add custom status type instead of PLAYING/WATCHING/...

### ISSUE THREAD

**Issue by TheJoshue** [Sayrix/Ticket-Bot#455]
Example from another bot:
![image](https://github.com/user-attachments/assets/719a7555-9df4-4f91-98b1-223c64e432c6)

**Comment by Sayrix** [comment]
just put CUSTOM in the type

**Comment by TheJoshue** [comment]
```jsonc
	"status": {
		"enabled": true, // If you want to enable the status of the bot
		"text": "Testing", // The text of the status
		"type": "CUSTOM", // PLAYING, WATCHING, LISTENING, STREAMING, COMPETING
		"url": "", // The url of the status if the type is STREAMING (can be blank)
		"status": "online" // online, idle, dnd, invisible set to online if the type is STREAMING
	},
```
i have restarted bot
![image](https://github.com/user-attachments/assets/355e5e0f-00eb-472c-8d2f-d2d4b1e1bf66)

**Comment by Sayrix** [comment]
Can you try with the latest commit?

**Comment by TheJoshue** [comment]
> Can you try with the latest commit?

when i try to build docker image:

 => ERROR [12/14] RUN npm run build                                                                8.0s
------
 > [12/14] RUN npm run build:
0.640
0.640 > ticket-bot@3.3.1 build
0.640 > rimraf dist && tsc
0.640
7.950 src/events/ready.ts(196,9): error TS2678: Type '"CUSTOM"' is not comparable to type '"PLAYING" | "STREAMING" | "LISTENING" | "WATCHING" | "COMPETING"'

**Comment by Sayrix** [comment]
Yeah my bad, can you retry with the latest commit?

**Comment by TheJoshue** [comment]
Nice!
I hope we move to https://github.com/Sayrix/Ticket-Bot/issues/454

![image](https://github.com/user-attachments/assets/b20b82bc-a2bf-4eab-946f-98d2ce38f085)
