### ISSUE TITLE
Launch problems

### ISSUE THREAD

**Issue by georgb15** [Sayrix/ticket-bot#51]
![изображение](https://user-images.githubusercontent.com/72269880/187320710-aa366f05-dd3e-43e6-b608-0f06a0d62a83.png)

**Comment by Migueldeeteenaa** [comment]
Maybe you have to use node index.js ?

**Comment by Sayrix** [comment]
Use Node LTS or Node Current

**Comment by Migueldeeteenaa** [comment]
What did you want to tell me? Sorry.

**Comment by Sayrix** [comment]
nevermind the user use Node Current

**Comment by Migueldeeteenaa** [comment]
Ok, thanks.

**Comment by Migueldeeteenaa** [comment]
Do you know why I have this problem?

TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role.
