### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by 6MJ9** [Sayrix/ticket-bot#58]
when starting program in nodejs this comes "Uncaught SyntaxError: Invalid or unexpected token" tokens are filled in properly

when running programm on jshint this error´s are found: 

Two warnings
--
20 | 'template literal syntax' is only available in ES6 (use 'esversion: 6').
19 | Unrecoverable syntax error. (73% scanned).
--

**Comment by Sayrix** [comment]
🤷
