### ISSUE TITLE
 You can only bulk delete messages that are under 14 days old.

### ISSUE THREAD

**Issue by Lequ1** [Sayrix/ticket-bot#6]
![image](https://user-images.githubusercontent.com/81021999/146648828-72a98a46-c477-4341-ab7e-1f1e34f53b29.png)

**Comment by Sayrix** [comment]
Hmm i will fix this

**Comment by Lequ1** [comment]
I found the bug in the channels were older messages sorry

**Comment by Lequ1** [comment]
I found the Error, in the Channels

**Comment by Sayrix** [comment]
I fixed the bug re download the [ready file](https://github.com/Sayrix/ticket-bot/blob/main/events/ready.js)
