### ISSUE TITLE
erreur lancement / error launching

### ISSUE THREAD

**Issue by InfiniteTools** [Sayrix/ticket-bot#71]
error when i try to launch the bot : 
C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main>node index.js

████████╗██╗ ██████╗██╗  ██╗███████╗████████╗    ██████╗  ██████╗ ████████╗
╚══██╔══╝██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝    ██╔══██╗██╔═══██╗╚══██╔══╝
   ██║   ██║██║     █████╔╝ █████╗     ██║       ██████╔╝██║   ██║   ██║
   ██║   ██║██║     ██╔═██╗ ██╔══╝     ██║       ██╔══██╗██║   ██║   ██║
   ██║   ██║╚██████╗██║  ██╗███████╗   ██║       ██████╔╝╚██████╔╝   ██║
   ╚═╝   ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚═════╝  ╚═════╝    ╚═╝
                    https://github.com/Sayrix/ticket-bot

Connecting to Discord...(node:12596) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:events:371
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'members')
    at Object.execute (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\events\ready.js:5:56)
    at Client.<anonymous> (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\index.js:87:46)
    at Object.onceWrapper (node:events:514:26)
    at Client.emit (node:events:394:28)
    at WebSocketManager.triggerClientReady (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:385:17)
    at WebSocketManager.checkShardsReady (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:368:10)
    at WebSocketShard.<anonymous> (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:194:14)
    at WebSocketShard.emit (node:events:394:28)
    at WebSocketShard.checkReady (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:511:12)
    at Object.module.exports [as READY] (C:\Users\bluet\Desktop\Bot Discord\ticket-bot-main\node_modules\discord.js\src\client\websocket\handlers\READY.js:26:9)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:254:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)

besoin d'aide stp / need help please

**Comment by Sayrix** [comment]
Show me your config.jsonc please

**Comment by InfiniteTools** [comment]
{
  "clientId": "1036739825077846147", // The id of the discord bot
  "guildId": "1035880560104579182", // The id of the discord server
  "mainColor": "f6c42f", // The hex color of the embeds by default
  "lang": "fr", // If you want to set english please set "main"


  "openTicketChannelId": "1036740715679592448", // The id of the channel where the message to create a ticket will be sent
  "ticketTypes": [ // You have a limit of 25 types (the limit of Discord)
    {
      "codeName": "suggestion", // The name need to be in lowercase
      "name": "Suggestion", // The name that will be displayed in the ticket
      "emoji": "💡", // The emoji of the type (can be blank)
      "color": "#e45671", // Can be a hex color or blank to use the main color
      "categoryId": "1036742267135856651", // The category id where the tickets will be created
      "customDescription": "S'il vous plait veuillez expliquer votre suggestion en détail. Si vous avez des images, s'il vous plait attachez les a votre message.\n\nRaison: RAISON", // The custom description of the ticket type (set to blank to use the default description)
      "askReason": true // If the bot should ask the reason of the ticket
    },
    {
      "codeName": "report", // The name need to be in lowercase
      "name": "Report", // The name that will be displayed in the ticket
      "emoji": "🛑", // The emoji of the type (can be blank)
      "color": "#f8312f", // Can be a hex color or blank to use the main color
      "categoryId": "1036742267135856651", // The category id where the tickets will be created
      "customDescription": "S'il vous plait veuillez expliquer votre report en détail. Si vous avez des images, s'il vous plait attachez les a votre message.\n\nRaison: RAISON",
      "askReason": false // If the bot should ask the reason of the ticket
    },
    {
      "codeName": "autre", // The name need to be in lowercase
      "name": "Autre", // The name that will be displayed in the ticket
      "emoji": "", // The emoji of the type (can be blank)
      "color": "", // Can be a hex color or blank to use the main color
      "categoryId": "1036742267135856651", // The category id where the tickets will be created
      "customDescription": "", // The custom description of the ticket type (set to blank to use the default description)
      "askReason": false // If the bot should ask the reason of the ticket
    }
  ],
  "ticketNameOption": "Ticket-TICKETCOUNT", // Here is all parameter: USERNAME, USERID, TICKETCOUNT
  "rolesWhoHaveAccessToTheTickets": [
    "1036589030973919232",
    "1036742995032150096"
  ], // Roles who can access to the tickets
  "pingRoleWhenOpened": true,
  "roleToPingWhenOpenedId": "1036589030973919232", // The role to ping when a ticket is opened
  "logs": true,
  "logsChannelId": "1035880560104579185", // The id of the channel where the logs will be sent
  "claimButton": true,
  "whoCanCloseTicket": "STAFFONLY", // STAFFONLY (roles configured at "rolesWhoHaveAccessToTheTickets") or EVERYONE
  "closeButton": true, // If false the ticket can be closed only by doing /closes
  "askReasonWhenClosing": true, // If false the ticket will be closed without asking the reason
  "maxTicketOpened": 2 // The number of tickets the user can open while another one is already open. Set to 0 to unlimited
}

**Comment by Sayrix** [comment]
Make sure that the guildId is correct and the bot is in the guild

**Comment by InfiniteTools** [comment]
oh thx its good
