### ISSUE TITLE
claim command and button dont work

### ISSUE THREAD

**Issue by InfiniteTools** [Sayrix/Ticket-Bot#73]
quand je clique sur claim cela me dis que seul les staffs peuvent claim sauf que j'ai le role que j'ai config etc donc je ne comprend pas pourquoi sa ne marche pas

**Comment by InfiniteTools** [comment]
config :


{
  "clientId": "1036739825077846147", // The id of the discord bot
  "guildId": "1038120164589309953", // The id of the discord server
  "mainColor": "f6c42f", // The hex color of the embeds by default
  "lang": "fr", // If you want to set english please set "main"


  "openTicketChannelId": "1038160570555314307", // The id of the channel where the message to create a ticket will be sent
  "ticketTypes": [ // You have a limit of 25 types (the limit of Discord)
    {
      "codeName": "suggestion", // The name need to be in lowercase
      "name": "Suggestion", // The name that will be displayed in the ticket
      "emoji": "💡", // The emoji of the type (can be blank)
      "color": "#e45671", // Can be a hex color or blank to use the main color
      "categoryId": "1038165939545440439", // The category id where the tickets will be created
      "customDescription": "S'il vous plait veuillez expliquer votre suggestion en détail. Si vous avez des images, s'il vous plait attachez les a votre message.\n\nRaison: RAISON", // The custom description of the ticket type (set to blank to use the default description)
      "askReason": true // If the bot should ask the reason of the ticket
    },
    {
      "codeName": "report", // The name need to be in lowercase
      "name": "Report", // The name that will be displayed in the ticket
      "emoji": "🛑", // The emoji of the type (can be blank)
      "color": "#f8312f", // Can be a hex color or blank to use the main color
      "categoryId": "1038165939545440439", // The category id where the tickets will be created
      "customDescription": "S'il vous plait veuillez expliquer votre report en détail. Si vous avez des images, s'il vous plait attachez les a votre message.\n\nRaison: RAISON",
      "askReason": true // If the bot should ask the reason of the ticket
    },
    {
      "codeName": "autre", // The name need to be in lowercase
      "name": "Autre", // The name that will be displayed in the ticket
      "emoji": "", // The emoji of the type (can be blank)
      "color": "", // Can be a hex color or blank to use the main color
      "categoryId": "1038165939545440439", // The category id where the tickets will be created
      "customDescription": "", // The custom description of the ticket type (set to blank to use the default description)
      "askReason": true // If the bot should ask the reason of the ticket
    }
  ],
  "ticketNameOption": "Ticket-TICKETCOUNT", // Here is all parameter: USERNAME, USERID, TICKETCOUNT
  "rolesWhoHaveAccessToTheTickets": [
    "1038158144062361722",
    "1038152736077791254"
  ], // Roles who can access to the tickets
  "pingRoleWhenOpened": true,
  "roleToPingWhenOpenedId": "1038158144062361722", // The role to ping when a ticket is opened
  "logs": true,
  "logsChannelId": "1038166284468236288", // The id of the channel where the logs will be sent
  "claimButton": true,
  "whoCanCloseTicket": "STAFFONLY", // STAFFONLY (roles configured at "rolesWhoHaveAccessToTheTickets") or EVERYONE
  "closeButton": true, // If false the ticket can be closed only by doing /closes
  "askReasonWhenClosing": true, // If false the ticket will be closed without asking the reason
  "maxTicketOpened": 2 // The number of tickets the user can open while another one is already open. Set to 0 to unlimited
}

**Comment by Sayrix** [comment]
Salut tu peux pas claim ton propre ticket c'est pour ça
