### ISSUE TITLE
When the bot cannot send the transcript to the private person because it has the DM closed, it turns off

### ISSUE THREAD

**Issue by Pipeeee1231** [Sayrix/ticket-bot#8]
![image](https://user-images.githubusercontent.com/83485167/146656009-ad72a8df-39a1-4811-833f-c88e92164a53.png)

**Comment by Sayrix** [comment]
Yes it's normal

**Comment by Pipeeee1231** [comment]
> Yes it's normal

Will you solve it?

**Comment by Sayrix** [comment]
I can't, it's just that the person has closed their DMs

**Comment by Pipeeee1231** [comment]
If you can, let the bot warn through the channel that the person has their dm closed and that it does not turn off.
