### ISSUE TITLE
Deploy Commands not Working.

### ISSUE THREAD

**Issue by hypezonnodejs** [Sayrix/Ticket-Bot#86]
I am typing node deploy-commands.js as well as just deploy-commands.js but the slash commands are not working I followed all the steps.

**Comment by thomasbnt** [comment]
Hello @hypezonnodejs, can you tell us more information about your error? Show the console error and your code.

**Comment by thomasbnt** [comment]
Maybe this PR resolve this issue, but don't hesitate to tell us more about your issue please :D
