### ISSUE TITLE
i have another issue when trying to start

### ISSUE THREAD

**Issue by brioch77** [Sayrix/Ticket-Bot#90]
████████╗██╗ ██████╗██╗  ██╗███████╗████████╗    ██████╗  ██████╗ ████████╗
╚══██╔══╝██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝    ██╔══██╗██╔═══██╗╚══██╔══╝
   ██║   ██║██║     █████╔╝ █████╗     ██║       ██████╔╝██║   ██║   ██║   
   ██║   ██║██║     ██╔═██╗ ██╔══╝     ██║       ██╔══██╗██║   ██║   ██║   
   ██║   ██║╚██████╗██║  ██╗███████╗   ██║       ██████╔╝╚██████╔╝   ██║   
   ╚═╝   ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚═════╝  ╚═════╝    ╚═╝
                    https://github.com/Sayrix/ticket-bot

Connecting to Discord...node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'members')
    at Object.execute (/Users/tommaso/Desktop/ZeroMC Bot/events/ready.js:8:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by Sayrix** [comment]
Show me your config.jsonc

**Comment by Sayrix** [comment]
Check that the guildId is correct or that the bot is in the guildId that you set

**Comment by brioch77** [comment]
I didn't save the file... thank you so much,now it has started
